comment:
  image:
    repository: werevolk/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: werevolk/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: werevolk/ui
    tag: latest
    service:
      externalPort: 9292
