global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitry_golovin'
